name: ssh
description: configures ssh known_hosts and private key

inputs:
  SSH_KEY:
    description: ssh private key to install
    required: true

runs:
  using: composite
  steps:
    - name: install known_hosts
      run: |
        mkdir -p ~/.ssh
        echo nebula-pink.bingecraft.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBCOPJsWQgUwrjWPxrmr9YkC83yWtmK/sTBIgFyOTXc7cdkkjoSVYFxycCCawNyv32Y9BkA0J+et6zjaLy/7a4HA= >> ~/.ssh/known_hosts
      shell: bash
    - name: install private key
      run: |
        SSH_KEY_FILE=~/.ssh/id_ed25519
        touch $SSH_KEY_FILE
        chmod 600 $SSH_KEY_FILE
        echo "${{ inputs.SSH_KEY }}" > $SSH_KEY_FILE
      shell: bash
