name: ssh
description: configures ssh known_hosts and private key

inputs:
  SSH_KEY:
    description: ssh private key to install
    required: true

runs:
  using: composite
  steps:
    - name: install known_hosts
      run: |
        mkdir -p ~/.ssh
        cat <<EOF >> ~/.ssh/known_hosts
        # nebula-blue.bingecraft.net:22 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5
        # nebula-blue.bingecraft.net:22 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5
        nebula-blue.bingecraft.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzTDMER+9dxee10DjVGKruESjvb7upR+1esZUpIzh6PSNadghW9PyYIj6sEFCE2EYHrqogsVN2kqDLy06LhdwOsgO8nR7TREP0+4UNNYa7dbkUJdqKpmXQMjM5pqsMHXPcXh1+5xSLWMAQmojF6nKfBJ0zDMimr3IgEypE2DtduZGuJxn2IF2u831is4fdT7jz+YjzztuVYry4fr8fVMXPGTtbfKgeSis/66X6u4FpZ4Wonutd5g2owUlePdOdGkE5M/4cnnjcKvGhP1D8v5bNmvrDo19Xjq3b+p22fYcpAduUMx1GMOW8O+Z78NtZ+ooha6A3tmLy1YB2LGZUKcsk9OtXTxynjKZJzVjzpM3/M0ebW1OlHCRRhusKKwQjpuZKDc1lwmgozPToi2XEQfFtfgecH/htqvKMYKSXXi2dHR7HCcT6yLvXhMQhoAkwTSX2Pw39s0jYK62H6pVjdgdpQ0lRZsUaubBfv9heGFMIYLy4BjMxXjMdss8wbcMVDW0=
        # nebula-blue.bingecraft.net:22 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5
        nebula-blue.bingecraft.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPq2qC/97w1eh8BIGTC02+DgTN477vqyDb+cTwu1OdvXagIR4Mh5dMsNYjFMtHejymA2ICd+qwdGW6ViJw4r/OI=
        # nebula-blue.bingecraft.net:22 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5
        nebula-blue.bingecraft.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMPf9xH2cpjE1VOtFQyyT8/APN/UFfh/WIXNfgVP8gvj
        # nebula-blue.bingecraft.net:22 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.5
        EOF
      shell: bash
    - name: install private key
      run: |
        SSH_KEY_FILE=~/.ssh/id_ed25519
        touch $SSH_KEY_FILE
        chmod 600 $SSH_KEY_FILE
        echo "${{ inputs.SSH_KEY }}" > $SSH_KEY_FILE
      shell: bash
