on:
  workflow_dispatch:
  push:
    branches: ["main"]

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ssh
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - id: check-target
        run: |
          source versions.zsh
          TARGET_DIR=$MONI_VERSION
          if ssh moni@nebula-pink.bingecraft.net -- ls $TARGET_DIR; then
            echo target directory already exists
          else
            echo TARGET=moni@nebula-pink.bingecraft.net:$TARGET_DIR >> "$GITHUB_OUTPUT"
          fi
    outputs:
      TARGET: ${{ steps.check-target.outputs.TARGET }}
  deploy:
    runs-on: ubuntu-latest
    needs: check-target
    if: ${{ needs.check-target.outputs.TARGET }}
    steps:
      - name: install zsh
        run: |
          sudo apt-get update && sudo apt-get install -y zsh && sudo apt-get clean
      - uses: actions/checkout@v4
      - uses: ./.github/actions/ssh
        with:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: |
          echo "export DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> secrets.zsh
          chmod +x secrets.zsh
          ./build.zsh
      - name: upload server files
        run: |
          rsync -avr \
            --include 'server/***' \
            --include backup-schedule.zsh \
            --include restore-latest-backup.zsh \
            --include run-accept-eula.zsh \
            --exclude '*' \
            ./ ${{ needs.check-target.outputs.TARGET }}/
